### ISSUE TITLE
[插件,Baymax ToOls] 表达式函数“Baymax ToOls.zero”注册失败……

### ISSUE THREAD

**Issue by sagasm** [sicaril/BaymaxTools#7]
环境：
win10 x64 22H2
x64dbg Nov 18 2023
Baymax tools v1.9

**Comment by sicaril** [comment]
Can you provide a screenshot? Thank you very much.

--------------------------------


----- 原始邮件 -----
发件人：sagasm ***@***.***>
收件人：sicaril/BaymaxTools ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[sicaril/BaymaxTools]_[插件,Baymax_ToOls]_表达式函数“Baymax_ToOls.zero”注册失败……_(Issue_#7)
日期：2023年11月18日 22点45分


环境：

win10 x64 22H2

x64dbg Nov 18 2023

Baymax tools v1.9

**Comment by sicaril** [comment]
This is not a bug, the plugin doesn't need to provide functionality for these interfaces, just remove it for the next version, thanks for the feedback.

--------------------------------


----- 原始邮件 -----
发件人：sagasm ***@***.***>
收件人：sicaril/BaymaxTools ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[sicaril/BaymaxTools]_[插件,Baymax_ToOls]_表达式函数“Baymax_ToOls.zero”注册失败……_(Issue_#7)
日期：2023年11月18日 22点45分


环境：

win10 x64 22H2

x64dbg Nov 18 2023

Baymax tools v1.9
