### ISSUE TITLE
搜索TMD加壳的程序有问题

### ISSUE THREAD

**Issue by kimo-zzz** [sicaril/BaymaxTools#8]
搜索TMD加壳后的程序 区段不正确会导致卡死 之前版本是崩溃新版本是卡死x96dbg 作者可以测试一下

**Comment by kimo-zzz** [comment]
![Uploading QQ截图20240524191053.png…]()
补充一张区段图

**Comment by sicaril** [comment]
我刚测试了themida的主程序，进行特征码搜索时未触发你说的卡死问题。区段不正确的意思是？内存中把PE头区段信息修改了 ？
另外你提供的[Uploading QQ截图20240524191053.png] 图片无法显示，可否把对应的程序+搜索数据+图片 打包到云盘，我去下载验证一下。
多谢反馈。

**Comment by kimo-zzz** [comment]
https://img2.imgtp.com/2024/05/25/9MGnugII.png 大概就是这个情况 区段的text data那些全部都是空格

**Comment by sicaril** [comment]
你想表达的问题是什么？区段名是允许为空的，你搜索了数据（所有的搜索数据，还是特定的）什么触发了卡死？我这里测试用的 themida 主程序，并未出现你描述的卡死现象。

**Comment by kimo-zzz** [comment]
搜索任意二进制数据都会造成卡死 我自己加的小demo不会出现卡死 只有当前文件到达一定大小才会(代码段达到一定大小才会触发吧)

**Comment by kimo-zzz** [comment]
错误应用程序名称: x64dbg.exe，版本: 0.0.2.5，时间戳: 0x661812fa
错误模块名称: BaymaxTools.dp64，版本: 1.0.0.1023，时间戳: 0x5e7ad988
异常代码: 0xc0000005
错误偏移量: 0x000000000000aa10
错误进程 ID: 0x2124
错误应用程序启动时间: 0x01daafd899ae79bb
错误应用程序路径: D:\Tools\x64dbg\x64\x64dbg.exe
错误模块路径: D:\Tools\x64dbg\x64\plugins\BaymaxTools.dp64
报告 ID: cc2408f7-e5b8-47c8-97ba-d26307c7df5c
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by kimo-zzz** [comment]
我用的是老版本测试 版本: 1.0.0.1023 对应的错误偏移量是2D0D8  我就不分析啦 作者你方便的话可以看看
DLL已载入： [00007FFC06C50000](x64dbg://localhost/address64#00007FFC06C50000) D:\Tools\x64dbg\x64\plugins\BaymaxTools.dp64
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: C0000005 (EXCEPTION_ACCESS_VIOLATION)
          ExceptionFlags: 00000000
        ExceptionAddress: baymaxtools.[00007FFC06C5AA10](x64dbg://localhost/address64#00007FFC06C5AA10)
        NumberParameters: 2
ExceptionInformation[00]: [0000000000000000](x64dbg://localhost/address64#0000000000000000) Read
ExceptionInformation[01]: [000001DB63FF2000](x64dbg://localhost/address64#000001DB63FF2000) Inaccessible Address
第一次异常于 [00007FFC06C5AA10](x64dbg://localhost/address64#00007FFC06C5AA10) (C0000005, EXCEPTION_ACCESS_VIOLATION)！
DLL已载入： [00007FFC6EAA0000](x64dbg://localhost/address64#00007FFC6EAA0000) C:\Windows\System32\version.dll
DLL已卸载： [00007FFC6EAA0000](x64dbg://localhost/address64#00007FFC6EAA0000) version.dll
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 0
           ExceptionCode: C0000409 (STATUS_STACK_BUFFER_OVERRUN)
          ExceptionFlags: 00000001
        ExceptionAddress: baymaxtools.[00007FFC06C7D0D8](x64dbg://localhost/address64#00007FFC06C7D0D8)
        NumberParameters: 1
ExceptionInformation[00]: [0000000000000002](x64dbg://localhost/address64#0000000000000002)
第二次异常于 [00007FFC06C7D0D8](x64dbg://localhost/address64#00007FFC06C7D0D8) (C0000409, STATUS_STACK_BUFFER_OVERRUN)！

**Comment by sicaril** [comment]
方便把文件或安装程序打包发我一份吗？（或者你试下哪些程序还能戳出这个问题，发我即可）。估计是程序内部做了什么修改了，用对应的程序来测试才能戳出这个BUG。

**Comment by sicaril** [comment]
BaymaxTools.dp64 最新版 1.0.0.1039，你用的是很久之前的版本，你更新成最新版再试试。
